name: note_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  device_preview: ^1.2.0
  hive_flutter: ^1.1.0
  flutter_bloc: ^8.1.6
  get: ^4.6.6  


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.9.2

flutter_icons:
  android: true
  image_path: "assets/note.png"

flutter:
  uses-material-design: true
  assets:
    - assets/note.png

